# -*- mode: ruby -*-
# # vi: set ft=ruby :

require 'fileutils'

Vagrant.require_version ">= 1.6.0"

CLOUD_CONFIG_PATH = File.join(File.dirname(__FILE__), "cloud-config.yaml")

# Defaults for config options defined in CONFIG
$update_channel = "alpha"
$enable_serial_logging = false
$vb_gui = false
$vb_memory = 1024
$vb_cpus = 1
$synced_folder = "."

$num_instances=1

$expose_app_tcp=5799

$expose_rdb_client=28015
$expose_rdb_cluster=29015
$expose_rdb_admin=8080

$expose_lookupd_http=4161
$expose_lookupd_tcp=4160
$expose_nsqd_http=4151
$expose_nsqd_tcp=4150

if ENV["SYNCED_FOLDER"]
    $synced_folder = ENV["SYNCED_FOLDER"]
end

Vagrant.configure("2") do |config|
  config.vm.box = "coreos-%s" % $update_channel
  config.vm.box_version = ">= 308.0.1"
  config.vm.box_url = "http://%s.release.core-os.net/amd64-usr/current/coreos_production_vagrant.json" % $update_channel

  config.vm.provider :vmware_fusion do |vb, override|
    override.vm.box_url = "http://%s.release.core-os.net/amd64-usr/current/coreos_production_vagrant_vmware_fusion.json" % $update_channel
  end

  config.vm.provider :virtualbox do |v|
    # On VirtualBox, we don't have guest additions or a functional vboxsf
    # in CoreOS, so tell Vagrant that so it can be smarter.
    v.check_guest_additions = false
    v.functional_vboxsf     = false
  end

  # plugin conflict
  if Vagrant.has_plugin?("vagrant-vbguest") then
    config.vbguest.auto_update = false
  end

  (1..$num_instances).each do |i|
    config.vm.define vm_name = "core-%02d" % i do |config|
      config.vm.hostname = vm_name

      if $enable_serial_logging
        logdir = File.join(File.dirname(__FILE__), "log")
        FileUtils.mkdir_p(logdir)

        serialFile = File.join(logdir, "%s-serial.txt" % vm_name)
        FileUtils.touch(serialFile)

        config.vm.provider :vmware_fusion do |v, override|
          v.vmx["serial0.present"] = "TRUE"
          v.vmx["serial0.fileType"] = "file"
          v.vmx["serial0.fileName"] = serialFile
          v.vmx["serial0.tryNoRxLoss"] = "FALSE"
        end

        config.vm.provider :virtualbox do |vb, override|
          vb.customize ["modifyvm", :id, "--uart1", "0x3F8", "4"]
          vb.customize ["modifyvm", :id, "--uartmode1", serialFile]
        end
      end

      if $expose_app_tcp
        config.vm.network "forwarded_port", guest: 5799, host: ($expose_app_tcp + i - 1), auto_correct: true
      end

      if $expose_rdb_client
        config.vm.network "forwarded_port", guest: 28015, host: ($expose_rdb_client + i - 1), auto_correct: true
      end

      if $expose_rdb_cluster
        config.vm.network "forwarded_port", guest: 29015, host: ($expose_rdb_cluster + i - 1), auto_correct: true
      end

      if $expose_rdb_admin
        config.vm.network "forwarded_port", guest: 8080, host: ($expose_rdb_admin + i - 1), auto_correct: true
      end

      if $expose_lookupd_http
        config.vm.network "forwarded_port", guest: 4161, host: ($expose_lookupd_http + i - 1), auto_correct: true
      end

      if $expose_lookupd_tcp
          config.vm.network "forwarded_port", guest: 4160, host: ($expose_lookupd_tcp + i - 1), auto_correct: true
      end

      if $expose_nsqd_http
          config.vm.network "forwarded_port", guest: 4151, host: ($expose_nsqd_http + i - 1), auto_correct: true
      end

      if $expose_nsqd_tcp
          config.vm.network "forwarded_port", guest: 4150, host: ($expose_nsqd_tcp + i - 1), auto_correct: true
      end

      config.vm.network "forwarded_port", guest: 7001, host: (7001 + i - 1), auto_correct: true
      config.vm.network "forwarded_port", guest: 4001, host: (4001 + i - 1), auto_correct: true

      config.vm.provider :vmware_fusion do |vb|
        vb.gui = $vb_gui
      end

      config.vm.provider :virtualbox do |vb|
        vb.gui = $vb_gui
        vb.memory = $vb_memory
        vb.cpus = $vb_cpus
      end

      ip = "172.17.8.#{i+100}"
      config.vm.network :private_network, ip: ip

      # Uncomment below to enable NFS for sharing the host machine into the coreos-vagrant VM.
      #config.vm.synced_folder ".", "/home/core/share", id: "core", :nfs => true, :mount_options => ['nolock,vers=3,udp']

      if File.exist?(CLOUD_CONFIG_PATH)
        config.vm.provision :file, :source => "#{CLOUD_CONFIG_PATH}", :destination => "/tmp/vagrantfile-user-data"
        config.vm.provision :shell, :inline => "mv /tmp/vagrantfile-user-data /var/lib/coreos-vagrant/", :privileged => true
      end

      config.vm.synced_folder $synced_folder, "/home/core/ircdd", type:"rsync"

      config.ssh.forward_agent = true

    end
  end
end
